import template from './esmx-shop-audit-dashboard.html.twig';
import './esmx-shop-audit-dashboard.scss';
import { buildSummaryCards } from './constants/summary-cards.constant';
import {
    productGridColumns,
    translationGridColumns,
    categoryGridColumns,
} from './constants/grid-columns.constant';

Shopware.Component.register('esmx-shop-audit-dashboard', {
    template,

    // Inject our custom API service so we can call backend audit endpoints
    inject: ['esmxShopAuditApiService'],

    mixins: [
        Shopware.Mixin.getByName('notification'),
    ],

    data() {
        return {
            isLoading: false,      // Controls global dashboard loading state
            isRunningScan: false,  // Controls scan button loading state
            dashboard: null,       // Stores dashboard data returned by API
            latestScan: null,      // Stores latest scan information
            loadError: null,       // Error message if dashboard fails to load
            scanError: null,       // Error message if scan execution fails
        };
    },

    computed: {
        // Translated title of the dashboard card
        cardTitle() {
            return this.$tc('esmx-shop-audit-ai.dashboard.cardTitle');
        },

        // Totals section of the audit results (counts of issues)
        totals() {
            return this.dashboard?.liveAudit?.totals ?? {};
        },

        // Metadata about the last audit execution
        meta() {
            return this.dashboard?.liveAudit?.meta ?? {};
        },

        // Detailed issue groups returned by the audit engine
        issues() {
            return this.dashboard?.liveAudit?.issues ?? {};
        },

        // AI-generated insights and recommendations
        insights() {
            return this.dashboard?.insights ?? {};
        },

        // Top recommended tasks generated by audit insights
        topTasks() {
            return this.insights.topTasks ?? [];
        },

        // Top findings detected in the latest scan
        topFindings() {
            return this.insights.topFindings ?? [];
        },

        // Short summary generated for the latest insights
        latestInsightSummary() {
            return this.insights.latestSummary ?? null;
        },

        // Number of currently open tasks
        openTaskCount() {
            return this.insights.openTaskCount ?? 0;
        },

        // Summary statistics from the most recent scan
        latestScanSummary() {
            return this.latestScan?.summaryJson ?? {};
        },

        // Configuration for dashboard metric cards
        // Each card represents a detected issue category
        summaryCards() {
            return buildSummaryCards(this.$tc.bind(this), this.totals);
        },

        // Grid column definition for product tables
        gridColumns() {
            return productGridColumns(this.$tc.bind(this));
        },

        // Grid configuration used for translation related audit results
        translationGridColumns() {
            return translationGridColumns(this.$tc.bind(this));
        },

        // Grid configuration used for category audit results
        categoryGridColumns() {
            return categoryGridColumns();
        },

        // Sales insights returned by backend (sales performance analysis)
        salesInsights() {
            return this.dashboard?.salesInsights ?? {};
        },

        // KPI metrics derived from sales insights
        salesKpis() {
            return {
                revenue: Number(this.salesInsights?.kpis?.revenue ?? 0),
                orders: Number(this.salesInsights?.kpis?.orders ?? 0),
                revenueChange: Number(this.salesInsights?.kpis?.revenueChange ?? 0),
                ordersChange: Number(this.salesInsights?.kpis?.ordersChange ?? 0),
            };
        },

        // List of top-selling products
        topSellingProducts() {
            return this.salesInsights?.topProducts ?? [];
        },

        // Bestsellers that are currently low on stock
        lowStockProducts() {
            return this.salesInsights?.lowStockBestSellers ?? [];
        },

        // Human-readable date of latest scan for trust and clarity in the UI
        formattedLatestScanDate() {
            const createdAt = this.latestScan?.createdAt;

            if (!createdAt) {
                return null;
            }

            return new Intl.DateTimeFormat(undefined, {
                year: 'numeric',
                month: 'short',
                day: '2-digit',
                hour: '2-digit',
                minute: '2-digit',
            }).format(new Date(createdAt));
        },

        // Summary cards sorted by severity first and count second, so most important issues appear first
        sortedSummaryCards() {
            const severityWeight = {
                critical: 4,
                high: 3,
                medium: 2,
                low: 1,
            };

            return [...this.summaryCards].sort((a, b) => {
                const severityDiff = (severityWeight[b.severity] || 0) - (severityWeight[a.severity] || 0);

                if (severityDiff !== 0) {
                    return severityDiff;
                }

                return (b.count || 0) - (a.count || 0);
            });
        },

        // Smart dashboard headline to explain the most important current shop status
        dashboardHeadline() {
            const outOfStock = this.totals.outOfStockProducts || 0;
            const missingDescription = this.totals.missingDescription || 0;
            const missingMetaTitle = this.totals.missingMetaTitle || 0;
            const missingPrice = this.totals.missingPrice || 0;

            if (outOfStock > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineOutOfStock', outOfStock, {
                    count: outOfStock,
                });
            }

            if (missingPrice > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineMissingPrice', missingPrice, {
                    count: missingPrice,
                });
            }

            if (missingDescription > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineMissingDescription', missingDescription, {
                    count: missingDescription,
                });
            }

            if (missingMetaTitle > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineMissingMetaTitle', missingMetaTitle, {
                    count: missingMetaTitle,
                });
            }

            return this.$tc('esmx-shop-audit-ai.dashboard.healthyHeadline');
        },

        // Suggest the next most useful action so the user knows what to do first
        nextBestAction() {
            if ((this.totals.outOfStockProducts || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionRestock'),
                    target: 'audit-section-out-of-stock-products',
                };
            }

            if ((this.totals.missingPrice || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionPrice'),
                    target: 'audit-section-missing-price',
                };
            }

            if ((this.totals.missingDescription || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionDescriptions'),
                    target: 'audit-section-missing-description',
                };
            }

            if ((this.totals.missingMetaTitle || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionSeo'),
                    target: 'audit-section-missing-meta-title',
                };
            }

            return null;
        },


    },

    // Lifecycle hook triggered when component is created
    created() {
        this.initializeDashboard();
    },

    methods: {
        // Initialize dashboard by loading main dashboard data and latest scan
        initializeDashboard() {
            this.loadError = null;
            this.scanError = null;

            this.refreshDashboard().catch(() => {
                // Errors are already handled in individual methods
            });
        },

        // Reload both dashboard summary and latest scan data together
        refreshDashboard() {
            return Promise.all([
                this.loadDashboard(),
                this.loadLatestScan(),
            ]);
        },

        // Fetch dashboard data from backend API
        loadDashboard() {
            this.isLoading = true;

            return this.esmxShopAuditApiService.getDashboard()
                .then((response) => {
                    this.dashboard = response;
                })
                .catch((error) => {
                    console.error('EsmxShopAuditAi dashboard error:', error);
                    this.loadError = this.$tc('esmx-shop-audit-ai.dashboard.loadError');
                    throw error;
                })
                .finally(() => {
                    this.isLoading = false;
                });
        },

        // Fetch information about the latest audit scan
        loadLatestScan() {
            return this.esmxShopAuditApiService.getLatestScan()
                .then((response) => {
                    this.latestScan = response.scan;
                })
                .catch((error) => {
                    console.error('EsmxShopAuditAi latest scan error:', error);
                    throw error;
                });
        },

        // Trigger a new audit scan and refresh dashboard data afterwards
        runScan() {
            this.isRunningScan = true;
            this.scanError = null;

            this.esmxShopAuditApiService.runScan()
                .then(() => this.refreshDashboard())
                .then(() => {
                    this.createNotificationSuccess({
                        message: this.$tc('esmx-shop-audit-ai.dashboard.runScanSuccess'),
                    });
                })
                .catch((error) => {
                    console.error('EsmxShopAuditAi run scan error:', error);
                    this.scanError = this.$tc('esmx-shop-audit-ai.dashboard.runScanError');

                    this.createNotificationError({
                        message: this.$tc('esmx-shop-audit-ai.dashboard.runScanError'),
                    });
                })
                .finally(() => {
                    console.log('runScan finished');
                    this.isRunningScan = false;
                });
        },

        // Navigation helpers to other plugin pages
        goToFindings() {
            this.$router.push({ name: 'esmx.shop.audit.ai.findings' });
        },

        goToTasks() {
            this.$router.push({ name: 'esmx.shop.audit.ai.tasks' });
        },

        goToReports() {
            this.$router.push({ name: 'esmx.shop.audit.ai.reports' });
        },

        goToSettings() {
            this.$router.push({ name: 'esmx.shop.audit.ai.settings' });
        },

        // Navigate to tasks page with filtering parameters
        goToTaskFilter(task) {
            this.$router.push({
                name: 'esmx.shop.audit.ai.tasks',
                query: {
                    priority: task.priority,
                    code: task.code,
                }
            });
        },

        // Navigate to findings page with filtering parameters
        goToFindingFilter(finding) {
            this.$router.push({
                name: 'esmx.shop.audit.ai.findings',
                query: {
                    severity: finding.severity,
                    code: finding.code,
                }
            });
        },

        // Scroll smoothly to a specific dashboard section
        scrollToSection(sectionId) {
            const section = document.getElementById(sectionId);

            if (!section) {
                return;
            }

            section.scrollIntoView({
                behavior: 'smooth',
                block: 'start',
            });
        },

        // Returns CSS class for severity styling
        getSeverityClass(severity) {
            return `esmx-shop-audit-dashboard__metric-card--${severity}`;
        },

        // Returns translated label for severity levels
        getSeverityLabel(severity) {
            return this.$tc(`esmx-shop-audit-ai.severity.${severity}`);
        },

        // Execute the suggested next action from the dashboard helper card
        handleNextBestAction() {
            if (!this.nextBestAction?.target) {
                return;
            }

            this.scrollToSection(this.nextBestAction.target);
        },
    }
});