import template from './esmx-shop-audit-dashboard.html.twig';
import './esmx-shop-audit-dashboard.scss';
import { buildSummaryCards } from './constants/summary-cards.constant';

Shopware.Component.register('esmx-shop-audit-dashboard', {
    template,

    // Inject our custom API service so we can call backend audit endpoints
    inject: ['esmxShopAuditApiService'],

    mixins: [
        Shopware.Mixin.getByName('notification'),
    ],

    data() {
        return {
            isLoading: false,               // Controls global dashboard loading state
            isRunningScan: false,           // Controls scan button loading state
            dashboard: null,                // Stores dashboard data returned by API
            latestScan: null,               // Stores latest scan information
            loadError: null,                // Error message if dashboard fails to load
            scanError: null,                // Error message if scan execution fails
            activeImpactKey: null,          // Controls summary card tooltip
            activeWidgetTooltip: null,      // Controls Widgets tooltip
            affectedProducts: 0,
            criticalIssues: 0,
            animatedHealthScore: 0,
        };
    },

    computed: {
        // Translated title of the dashboard card
        //cardTitle() {
          //  return this.$tc('esmx-shop-audit-ai.dashboard.cardTitle');
        //},

        // Totals section of the audit results (counts of issues)
        totals() {
            return this.dashboard?.liveAudit?.totals ?? {};
        },

        // Metadata about the last audit execution
        meta() {
            return this.dashboard?.liveAudit?.meta ?? {};
        },

        // AI-generated insights and recommendations
        insights() {
            return this.dashboard?.insights ?? {};
        },

        // Top recommended tasks generated by audit insights
        topTasks() {
            return this.insights.topTasks ?? [];
        },

        // Number of currently open tasks
        openTaskCount() {
            return this.insights.openTaskCount ?? 0;
        },

        // Section 1: top scan overview counters shown in the full-width header card
        scanOverviewStats() {
            return [
                {
                    key: 'scannedProducts',
                    label: this.$tc('esmx-shop-audit-ai.dashboardInsights.scannedProducts'),
                    value: this.latestScan?.scannedProducts || 0,
                },
                {
                    key: 'affectedProducts',
                    label: this.$tc('esmx-shop-audit-ai.dashboardInsights.affectedProducts'),
                    value: this.affectedProducts,
                },
                {
                    key: 'totalIssues',
                    label: this.$tc('esmx-shop-audit-ai.dashboard.totalIssues'),
                    value: this.totals.totalIssues || 0,
                },
                {
                    key: 'criticalIssues',
                    label: this.$tc('esmx-shop-audit-ai.dashboardInsights.criticalIssues'),
                    value: this.criticalIssues,
                },
                {
                    key: 'issueGroups',
                    label: this.$tc('esmx-shop-audit-ai.dashboard.issueGroups'),
                    value: this.sortedSummaryCards.length,
                },
                {
                    key: 'openTasks',
                    label: this.$tc('esmx-shop-audit-ai.dashboardInsights.openTasks'),
                    value: this.openTaskCount,
                },
            ];
        },

        // Configuration for dashboard metric cards
        // Each card represents a detected issue category
        summaryCards() {
            return buildSummaryCards(this.$tc.bind(this), this.totals);
        },

        // Sales insights returned by backend (sales performance analysis)
        salesInsights() {
            return this.dashboard?.salesInsights ?? {};
        },

        // KPI metrics derived from sales insights
        salesKpis() {
            return {
                revenue: Number(this.salesInsights?.kpis?.revenue ?? 0),
                orders: Number(this.salesInsights?.kpis?.orders ?? 0),
                revenueChange: Number(this.salesInsights?.kpis?.revenueChange ?? 0),
                ordersChange: Number(this.salesInsights?.kpis?.ordersChange ?? 0),
            };
        },

        // List of top-selling products
        topSellingProducts() {
            return this.salesInsights?.topProducts ?? [];
        },

        // Bestsellers that are currently low on stock
        lowStockProducts() {
            return this.salesInsights?.lowStockBestSellers ?? [];
        },

        // Human-readable date of latest scan for trust and clarity in the UI
        formattedLatestScanDate() {
            const scanDate = this.latestScan?.finishedAt || this.latestScan?.startedAt || null;

            if (!scanDate) {
                return null;
            }

            return new Intl.DateTimeFormat(undefined, {
                year: 'numeric',
                month: 'short',
                day: '2-digit',
                hour: '2-digit',
                minute: '2-digit',
            }).format(new Date(scanDate));
        },

        // Summary cards sorted by severity first and count second, so most important issues appear first
        sortedSummaryCards() {
            const severityWeight = {
                critical: 4,
                high: 3,
                medium: 2,
                low: 1,
            };

            return [...this.summaryCards].sort((a, b) => {
                const severityDiff = (severityWeight[b.severity] || 0) - (severityWeight[a.severity] || 0);

                if (severityDiff !== 0) {
                    return severityDiff;
                }

                return (b.count || 0) - (a.count || 0);
            });
        },

        // Smart dashboard headline to explain the most important current shop status
        dashboardHeadline() {
            const outOfStock = this.totals.outOfStockProducts || 0;
            const missingDescription = this.totals.missingDescription || 0;
            const missingMetaTitle = this.totals.missingMetaTitle || 0;
            const missingPrice = this.totals.missingPrice || 0;

            if (outOfStock > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineOutOfStock', outOfStock, {
                    count: outOfStock,
                });
            }

            if (missingPrice > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineMissingPrice', missingPrice, {
                    count: missingPrice,
                });
            }

            if (missingDescription > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineMissingDescription', missingDescription, {
                    count: missingDescription,
                });
            }

            if (missingMetaTitle > 0) {
                return this.$tc('esmx-shop-audit-ai.dashboard.headlineMissingMetaTitle', missingMetaTitle, {
                    count: missingMetaTitle,
                });
            }

            return this.$tc('esmx-shop-audit-ai.dashboard.healthyHeadline');
        },

        // Section 2: determines the most urgent action for the store health card
        nextBestAction() {
            if ((this.totals.outOfStockProducts || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionRestock'),
                    code: 'outOfStockProducts',
                };
            }

            if ((this.totals.missingPrice || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionPrice'),
                    code: 'missingPrice',
                };
            }

            if ((this.totals.missingDescription || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionDescriptions'),
                    code: 'missingDescription',
                };
            }

            if ((this.totals.missingMetaTitle || 0) > 0) {
                return {
                    label: this.$tc('esmx-shop-audit-ai.dashboard.nextActionSeo'),
                    code: 'missingMetaTitle',
                };
            }

            return null;
        },

        healthScore() {
            let score = 100;

            score -= Math.min((this.totals.outOfStockProducts || 0) * 3, 30);
            score -= Math.min((this.totals.missingPrice || 0) * 4, 25);
            score -= Math.min((this.totals.inactiveProducts || 0) * 3, 20);
            score -= Math.min((this.totals.missingDescription || 0) * 1, 10);
            score -= Math.min((this.totals.missingCoverImage || 0) * 1, 8);
            score -= Math.min((this.totals.missingMetaTitle || 0) * 1, 7);
            score -= Math.min((this.totals.missingCategory || 0) * 2, 12);
            score -= Math.min((this.totals.missingManufacturer || 0) * 1, 8);
            score -= Math.min((this.totals.missingTranslation || 0) * 1, 10);
            score -= Math.min((this.criticalIssues || 0) * 4, 20);

            return Math.max(0, Math.round(score));
        },

        healthStatus() {
            if (this.healthScore >= 85) {
                return 'good';
            }

            if (this.healthScore >= 60) {
                return 'warning';
            }

            return 'critical';
        },

        healthStatusLabel() {
            return this.$tc(`esmx-shop-audit-ai.dashboard.healthStatus.${this.healthStatus}`);
        },

        healthSummaryText() {
            if (this.healthStatus === 'good') {
                return this.$tc('esmx-shop-audit-ai.dashboard.healthSummaryGood');
            }

            if (this.healthStatus === 'warning') {
                return this.$tc('esmx-shop-audit-ai.dashboard.healthSummaryWarning');
            }

            return this.$tc('esmx-shop-audit-ai.dashboard.healthSummaryCritical');
        },

        healthRingStyle() {
            const score = Math.max(0, Math.min(this.animatedHealthScore, 100));
            let angle = Math.round((score / 100) * 360);

            if (score === 0) {
                angle = 6;
            }

            let color = '#10b981';

            if (this.healthStatus === 'warning') {
                color = '#f59e0b';
            }

            if (this.healthStatus === 'critical') {
                color = '#ef4444';
            }

            return {
                background: `conic-gradient(${color} 0deg ${angle}deg, #e5e7eb ${angle}deg 360deg)`,
            };
        },

    },

    // Lifecycle hook triggered when component is created
    created() {
        this.initializeDashboard();
    },

    methods: {
        // Initialize dashboard by loading main dashboard data and latest scan
        initializeDashboard() {
            this.loadError = null;
            this.scanError = null;

            this.refreshDashboard().catch(() => {
                // Errors are already handled in individual methods
            });
        },

        // Reload both dashboard summary and latest scan data together
        refreshDashboard() {
            return Promise.all([
                this.loadDashboard(),
                this.loadLatestScan(),
            ]);
        },

        // Fetch dashboard data from backend API
        loadDashboard() {
            this.isLoading = true;

            return this.esmxShopAuditApiService.getDashboard()
                .then((response) => {
                    this.dashboard = response;
                    this.affectedProducts = response?.insights?.affectedProducts || 0;
                    this.criticalIssues = response?.insights?.criticalIssues || 0;

                    this.$nextTick(() => {
                        this.animateHealthScore();
                    });
                })
                .catch((error) => {
                    console.error('EsmxShopAuditAi dashboard error:', error);
                    this.loadError = this.$tc('esmx-shop-audit-ai.dashboard.loadError');
                    throw error;
                })
                .finally(() => {
                    this.isLoading = false;
                });
        },

        // Fetch information about the latest audit scan
        loadLatestScan() {
            return this.esmxShopAuditApiService.getLatestScan()
                .then((response) => {
                    this.latestScan = response?.scan || null;
                })
                .catch((error) => {
                    console.error('EsmxShopAuditAi latest scan error:', error);
                    throw error;
                });
        },

        // Trigger a new audit scan and refresh dashboard data afterwards
        runScan() {
            this.isRunningScan = true;
            this.scanError = null;

            this.esmxShopAuditApiService.runScan()
                .then(() => this.refreshDashboard())
                .then(() => {
                    this.createNotificationSuccess({
                        message: this.$tc('esmx-shop-audit-ai.dashboard.runScanSuccess'),
                    });
                })
                .catch((error) => {
                    console.error('EsmxShopAuditAi run scan error:', error);
                    this.scanError = this.$tc('esmx-shop-audit-ai.dashboard.runScanError');

                    this.createNotificationError({
                        message: this.$tc('esmx-shop-audit-ai.dashboard.runScanError'),
                    });
                })
                .finally(() => {
                    this.isRunningScan = false;
                });
        },

        // Navigation helpers to other plugin pages
        goToFindings() {
            this.$router.push({ name: 'esmx.shop.audit.ai.findings' });
        },

        goToTasks() {
            this.$router.push({ name: 'esmx.shop.audit.ai.tasks' });
        },

        goToReports() {
            this.$router.push({ name: 'esmx.shop.audit.ai.reports' });
        },

        goToSettings() {
            this.$router.push({ name: 'esmx.shop.audit.ai.settings' });
        },

        // Navigate to tasks page with filtering parameters
        goToTaskFilter(task) {
            this.$router.push({
                name: 'esmx.shop.audit.ai.tasks',
                query: {
                    priority: task.priority,
                    code: task.code,
                }
            });
        },

        // Returns CSS class for severity styling
        getSeverityClass(severity) {
            return `esmx-shop-audit-dashboard__metric-card--${severity}`;
        },

        // Returns translated label for severity levels
        getSeverityLabel(severity) {
            return this.$tc(`esmx-shop-audit-ai.severity.${severity}`);
        },

        // Execute the suggested next action from the dashboard helper card
        handleNextBestAction() {
            if (!this.nextBestAction?.code) {
                return;
            }

            this.$router.push({
                name: 'esmx.shop.audit.ai.findings',
                query: {
                    code: this.nextBestAction.code,
                },
            });
        },

        // Open Shopware product detail page in administration
        goToProductDetail(productId) {
            if (!productId) {
                return;
            }

            this.$router.push({
                name: 'sw.product.detail',
                params: {
                    id: productId,
                },
            });
        },

        // Format currency values for dashboard KPIs
        formatCurrency(value) {
            if (value === null || value === undefined) {
                return '0.00';
            }

            return Number(value).toLocaleString(undefined, {
                minimumFractionDigits: 2,
                maximumFractionDigits: 2
            });
        },

        // Open Findings page filtered by summary card code and severity
        goToFindingFromCard(card) {
            if (!card?.code) {
                return;
            }

            this.$router.push({
                name: 'esmx.shop.audit.ai.findings',
                query: {
                    code: card.code,
                },
            });
        },

        animateHealthScore() {
            const target = Math.max(0, Math.min(this.healthScore, 100));
            const duration = 900;
            const start = this.animatedHealthScore;
            const startTime = performance.now();

            const animate = (currentTime) => {
                const elapsed = currentTime - startTime;
                const progress = Math.min(elapsed / duration, 1);

                // ease-out animation
                const easedProgress = 1 - Math.pow(1 - progress, 3);

                this.animatedHealthScore = Math.round(start + ((target - start) * easedProgress));

                if (progress < 1) {
                    window.requestAnimationFrame(animate);
                    return;
                }

                this.animatedHealthScore = target;
            };

            window.requestAnimationFrame(animate);
        },
    }
});